project/board/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view()),
    # path('new/', NewOrderView.as_view(), name='new_order'),
    # path('take/<int:oid>', take_order, name='take_order')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from simpleapp.views import multiply

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом products/.
    path('products/', include('simpleapp.urls')),
    path('multiply/', multiply),
    path('accounts/', include('allauth.urls')),
    path("accounts/", include("accounts.urls")),
    path('board/', include('board.urls'))
]

project/board/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField(default=0.0)

    def __str__(self):
        return self.name + "/" + str(self.price)


class Order(models.Model):
    time_in = models.DateTimeField(auto_now_add=True)
    time_out = models.DateTimeField(null=True)
    cost = models.FloatField(default=0.0)
    take_away = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)

    products = models.ManyToManyField(Product, through='ProductOrder')


class ProductOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

project/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/products.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}
<!-- Название у нас будет products -->
{% block title %}
Products
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
    <h1>Все товары</h1>
    <h3>{% current_time %}</h3>
    <!-- Если в переменной next_sale будет None,
    то выведется указанный в фильтре текст -->
    <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>
    <form action="" method="get" >
        {{ filterset.form.non_field_errors }}

        {{ filterset.form.name__icontains.errors }}
        <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>
        <input
            id="{{ filterset.form.name__icontains.id }}"
            name="{{ filterset.form.name__icontains.name }}"
            value="{{ filterset.form.name__icontains.value }}"
            class="form-control"
        >
        <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>

    <hr>

    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.simpleapp.add_product %}
    <a href="{% url 'product_create' %}">Добавить товар</a>
    {% endif %}

    <!-- Выводим товары, только если они есть с помощью тега if -->
    {% if products %}
        <table> <!-- Начинаем описывать таблицу -->
            <tr> <!-- Добавляем строку -->
                <td>Название</td>
                <td>Описание</td>
                <td>Категория</td>
                <td>Цена</td>
                <td>Количество</td>
                {# Условие получается составным. #}
                {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
                <td>Действия</td>
                {% endif %}
            </tr> <!-- Не забываем закрыть HTML-тег строки -->

            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.description|truncatechars:15 }}</td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.price|currency:"usd" }}</td>
                <td>{{ product.quantity }}</td>
                <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.simpleapp.change_product %}
                    <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.simpleapp.delete_product %}
                    <a href="{% url 'product_delete' product.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table> <!-- ... и таблицы -->
    {% else %}
        <!-- Если товаров нет, говорим, что товаров нет ;) -->
        <h2>Товаров нет!</h2>
    {% endif %}
    {# Добавляем пагинацию на страницу #}

    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
        {# Для каждой ссылки пагинации указываем обработку через новый тег #}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}